<?php exit;?>08-30 12:19:25 | 2 | mysqli_connect(): Headers and client library minor version mismatch. Headers:50552 Library:50631 | /home/www/publics/publics/admin_hd/install_package/install/install.php | 359
<?php exit;?>08-30 12:19:25 | 2 | mysqli_connect(): Headers and client library minor version mismatch. Headers:50552 Library:50631 | /home/www/publics/publics/admin_hd/install_package/install/install.php | 212
<?php exit;?>08-30 12:19:26 | 2 | mysqli_connect(): Headers and client library minor version mismatch. Headers:50552 Library:50631 | /home/www/publics/publics/admin_hd/install_package/install/install.php | 286
<?php exit;?>08-30 12:19:26 | 2 | file_put_contents(/home/www/publics/publics/admin_hd/install_package/phpcms/../phpsso_server/caches/caches_admin/caches_data/applist.cache.php): failed to open stream: No such file or directory | /home/www/publics/publics/admin_hd/install_package/install/install.php | 324
<?php exit;?>08-30 12:19:26 | 2 | mysqli::__construct(): Headers and client library minor version mismatch. Headers:50552 Library:50631 | /home/www/publics/publics/admin_hd/install_package/phpcms/libs/classes/db_mysqli.class.php | 55
<?php exit;?>08-30 12:19:26 | 2 | mysqli::__construct(): Headers and client library minor version mismatch. Headers:50552 Library:50631 | /home/www/publics/publics/admin_hd/install_package/phpcms/libs/classes/db_mysqli.class.php | 55
<?php exit;?>08-30 12:19:26 | 2 | mysqli::__construct(): Headers and client library minor version mismatch. Headers:50552 Library:50631 | /home/www/publics/publics/admin_hd/install_package/phpcms/libs/classes/db_mysqli.class.php | 55
<?php exit;?>08-30 12:19:26 | 2 | mysqli::__construct(): Headers and client library minor version mismatch. Headers:50552 Library:50631 | /home/www/publics/publics/admin_hd/install_package/phpcms/libs/classes/db_mysqli.class.php | 55
<?php exit;?>08-30 12:19:26 | 2 | mysqli::__construct(): Headers and client library minor version mismatch. Headers:50552 Library:50631 | /home/www/publics/publics/admin_hd/install_package/phpcms/libs/classes/db_mysqli.class.php | 55
<?php exit;?>08-30 12:19:26 | 2 | mysqli::__construct(): Headers and client library minor version mismatch. Headers:50552 Library:50631 | /home/www/publics/publics/admin_hd/install_package/phpcms/libs/classes/db_mysqli.class.php | 55
<?php exit;?>08-30 12:19:26 | 2 | mysqli::__construct(): Headers and client library minor version mismatch. Headers:50552 Library:50631 | /home/www/publics/publics/admin_hd/install_package/phpcms/libs/classes/db_mysqli.class.php | 55
<?php exit;?>08-30 12:19:27 | 2 | mysqli::__construct(): Headers and client library minor version mismatch. Headers:50552 Library:50631 | /home/www/publics/publics/admin_hd/install_package/phpcms/libs/classes/db_mysqli.class.php | 55
<?php exit;?>08-30 12:19:27 | 2 | mysqli::__construct(): Headers and client library minor version mismatch. Headers:50552 Library:50631 | /home/www/publics/publics/admin_hd/install_package/phpcms/libs/classes/db_mysqli.class.php | 55
<?php exit;?>08-30 12:19:39 | 2 | mysqli::__construct(): Headers and client library minor version mismatch. Headers:50552 Library:50631 | phpcms/libs/classes/db_mysqli.class.php | 55
<?php exit;?>08-30 12:19:39 | 2 | mysqli::__construct(): Headers and client library minor version mismatch. Headers:50552 Library:50631 | phpcms/libs/classes/db_mysqli.class.php | 55
<?php exit;?>08-30 12:19:42 | 2 | mysqli::__construct(): Headers and client library minor version mismatch. Headers:50552 Library:50631 | phpcms/libs/classes/db_mysqli.class.php | 55
<?php exit;?>08-30 12:19:42 | 2 | mysqli::__construct(): Headers and client library minor version mismatch. Headers:50552 Library:50631 | phpcms/libs/classes/db_mysqli.class.php | 55
<?php exit;?>08-30 12:19:42 | 2 | mysqli::__construct(): Headers and client library minor version mismatch. Headers:50552 Library:50631 | phpcms/libs/classes/db_mysqli.class.php | 55
<?php exit;?>08-30 12:19:42 | 2 | mysqli::__construct(): Headers and client library minor version mismatch. Headers:50552 Library:50631 | phpcms/libs/classes/db_mysqli.class.php | 55
<?php exit;?>08-30 12:19:59 | 2 | mysqli::__construct(): Headers and client library minor version mismatch. Headers:50552 Library:50631 | phpcms/libs/classes/db_mysqli.class.php | 55
<?php exit;?>08-30 12:19:59 | 2 | mysqli::__construct(): Headers and client library minor version mismatch. Headers:50552 Library:50631 | phpcms/libs/classes/db_mysqli.class.php | 55
<?php exit;?>08-30 12:20:00 | 2 | mysqli::__construct(): Headers and client library minor version mismatch. Headers:50552 Library:50631 | phpcms/libs/classes/db_mysqli.class.php | 55
<?php exit;?>08-30 12:20:00 | 2 | mysqli::__construct(): Headers and client library minor version mismatch. Headers:50552 Library:50631 | phpcms/libs/classes/db_mysqli.class.php | 55
<?php exit;?>08-30 12:20:00 | 2 | mysqli::__construct(): Headers and client library minor version mismatch. Headers:50552 Library:50631 | phpcms/libs/classes/db_mysqli.class.php | 55
<?php exit;?>08-30 12:20:00 | 2 | mysqli::__construct(): Headers and client library minor version mismatch. Headers:50552 Library:50631 | phpcms/libs/classes/db_mysqli.class.php | 55
<?php exit;?>08-30 12:20:00 | 2 | mysqli::__construct(): Headers and client library minor version mismatch. Headers:50552 Library:50631 | phpcms/libs/classes/db_mysqli.class.php | 55
<?php exit;?>08-30 12:20:00 | 2 | mysqli::__construct(): Headers and client library minor version mismatch. Headers:50552 Library:50631 | phpcms/libs/classes/db_mysqli.class.php | 55
<?php exit;?>08-30 12:22:41 | 2 | mysqli::__construct(): Headers and client library minor version mismatch. Headers:50552 Library:50631 | phpcms/libs/classes/db_mysqli.class.php | 55
<?php exit;?>08-30 12:22:41 | 2 | mysqli::__construct(): Headers and client library minor version mismatch. Headers:50552 Library:50631 | phpcms/libs/classes/db_mysqli.class.php | 55
<?php exit;?>08-30 12:25:24 | 2 | mysqli::__construct(): Headers and client library minor version mismatch. Headers:50552 Library:50631 | phpcms/libs/classes/db_mysqli.class.php | 55
<?php exit;?>08-30 12:25:24 | 2 | mysqli::__construct(): Headers and client library minor version mismatch. Headers:50552 Library:50631 | phpcms/libs/classes/db_mysqli.class.php | 55
<?php exit;?>08-30 12:28:03 | 2 | mysqli::__construct(): Headers and client library minor version mismatch. Headers:50552 Library:50631 | phpcms/libs/classes/db_mysqli.class.php | 55
<?php exit;?>08-30 12:28:03 | 2 | mysqli::__construct(): Headers and client library minor version mismatch. Headers:50552 Library:50631 | phpcms/libs/classes/db_mysqli.class.php | 55
<?php exit;?>08-30 12:30:41 | 2 | mysqli::__construct(): Headers and client library minor version mismatch. Headers:50552 Library:50631 | phpcms/libs/classes/db_mysqli.class.php | 55
<?php exit;?>08-30 12:30:41 | 2 | mysqli::__construct(): Headers and client library minor version mismatch. Headers:50552 Library:50631 | phpcms/libs/classes/db_mysqli.class.php | 55
<?php exit;?>08-30 12:33:20 | 2 | mysqli::__construct(): Headers and client library minor version mismatch. Headers:50552 Library:50631 | phpcms/libs/classes/db_mysqli.class.php | 55
<?php exit;?>08-30 12:33:20 | 2 | mysqli::__construct(): Headers and client library minor version mismatch. Headers:50552 Library:50631 | phpcms/libs/classes/db_mysqli.class.php | 55
<?php exit;?>10-18 09:31:07 | 2 | file_put_contents(/project/publics/admin_hd/install_package/caches/caches_template/default/content/message.php): failed to open stream: Permission denied | phpcms/libs/classes/template_cache.class.php | 42
<?php exit;?>10-18 09:31:07 | 2 | chmod(): No such file or directory | phpcms/libs/classes/template_cache.class.php | 43
<?php exit;?>10-18 09:31:07 | 2 | include(/project/publics/admin_hd/install_package/caches/caches_template/default/content/message.php): failed to open stream: No such file or directory | phpcms/libs/functions/global.func.php | 555
<?php exit;?>10-18 09:31:07 | 2 | include(): Failed opening '/project/publics/admin_hd/install_package/caches/caches_template/default/content/message.php' for inclusion (include_path='.:/usr/local/php/lib/php') | phpcms/libs/functions/global.func.php | 555
<?php exit;?>10-18 09:32:24 | 2 | file_put_contents(/project/publics/admin_hd/install_package/caches/caches_template/default/content/message.php): failed to open stream: Permission denied | phpcms/libs/classes/template_cache.class.php | 42
<?php exit;?>10-18 09:32:24 | 2 | chmod(): No such file or directory | phpcms/libs/classes/template_cache.class.php | 43
<?php exit;?>10-18 09:32:24 | 2 | include(/project/publics/admin_hd/install_package/caches/caches_template/default/content/message.php): failed to open stream: No such file or directory | phpcms/libs/functions/global.func.php | 555
<?php exit;?>10-18 09:32:24 | 2 | include(): Failed opening '/project/publics/admin_hd/install_package/caches/caches_template/default/content/message.php' for inclusion (include_path='.:/usr/local/php/lib/php') | phpcms/libs/functions/global.func.php | 555
<?php exit;?>10-18 09:32:38 | 2 | file_put_contents(/project/publics/admin_hd/install_package/caches/caches_template/default/content/message.php): failed to open stream: Permission denied | phpcms/libs/classes/template_cache.class.php | 42
<?php exit;?>10-18 09:32:38 | 2 | chmod(): No such file or directory | phpcms/libs/classes/template_cache.class.php | 43
<?php exit;?>10-18 09:32:38 | 2 | include(/project/publics/admin_hd/install_package/caches/caches_template/default/content/message.php): failed to open stream: No such file or directory | phpcms/libs/functions/global.func.php | 555
<?php exit;?>10-18 09:32:38 | 2 | include(): Failed opening '/project/publics/admin_hd/install_package/caches/caches_template/default/content/message.php' for inclusion (include_path='.:/usr/local/php/lib/php') | phpcms/libs/functions/global.func.php | 555
<?php exit;?>10-18 09:32:53 | 2 | file_put_contents(/project/publics/admin_hd/install_package/caches/caches_template/default/content/message.php): failed to open stream: Permission denied | phpcms/libs/classes/template_cache.class.php | 42
<?php exit;?>10-18 09:32:53 | 2 | chmod(): No such file or directory | phpcms/libs/classes/template_cache.class.php | 43
<?php exit;?>10-18 09:32:53 | 2 | include(/project/publics/admin_hd/install_package/caches/caches_template/default/content/message.php): failed to open stream: No such file or directory | phpcms/libs/functions/global.func.php | 555
<?php exit;?>10-18 09:32:53 | 2 | include(): Failed opening '/project/publics/admin_hd/install_package/caches/caches_template/default/content/message.php' for inclusion (include_path='.:/usr/local/php/lib/php') | phpcms/libs/functions/global.func.php | 555
<?php exit;?>10-18 09:33:15 | 2 | file_put_contents(/project/publics/admin_hd/install_package/caches/caches_template/default/content/message.php): failed to open stream: Permission denied | phpcms/libs/classes/template_cache.class.php | 42
<?php exit;?>10-18 09:33:15 | 2 | chmod(): No such file or directory | phpcms/libs/classes/template_cache.class.php | 43
<?php exit;?>10-18 09:33:15 | 2 | include(/project/publics/admin_hd/install_package/caches/caches_template/default/content/message.php): failed to open stream: No such file or directory | phpcms/libs/functions/global.func.php | 555
<?php exit;?>10-18 09:33:15 | 2 | include(): Failed opening '/project/publics/admin_hd/install_package/caches/caches_template/default/content/message.php' for inclusion (include_path='.:/usr/local/php/lib/php') | phpcms/libs/functions/global.func.php | 555
<?php exit;?>10-18 09:33:36 | 2 | file_put_contents(/project/publics/admin_hd/install_package/caches/caches_template/default/content/message.php): failed to open stream: Permission denied | phpcms/libs/classes/template_cache.class.php | 42
<?php exit;?>10-18 09:33:36 | 2 | chmod(): No such file or directory | phpcms/libs/classes/template_cache.class.php | 43
<?php exit;?>10-18 09:33:36 | 2 | include(/project/publics/admin_hd/install_package/caches/caches_template/default/content/message.php): failed to open stream: No such file or directory | phpcms/libs/functions/global.func.php | 555
<?php exit;?>10-18 09:33:36 | 2 | include(): Failed opening '/project/publics/admin_hd/install_package/caches/caches_template/default/content/message.php' for inclusion (include_path='.:/usr/local/php/lib/php') | phpcms/libs/functions/global.func.php | 555
<?php exit;?>10-18 09:34:39 | 2 | file_put_contents(/project/publics/admin_hd/install_package/caches/caches_template/default/content/message.php): failed to open stream: Permission denied | phpcms/libs/classes/template_cache.class.php | 42
<?php exit;?>10-18 09:34:39 | 2 | chmod(): No such file or directory | phpcms/libs/classes/template_cache.class.php | 43
<?php exit;?>10-18 09:34:39 | 2 | include(/project/publics/admin_hd/install_package/caches/caches_template/default/content/message.php): failed to open stream: No such file or directory | phpcms/libs/functions/global.func.php | 555
<?php exit;?>10-18 09:34:39 | 2 | include(): Failed opening '/project/publics/admin_hd/install_package/caches/caches_template/default/content/message.php' for inclusion (include_path='.:/usr/local/php/lib/php') | phpcms/libs/functions/global.func.php | 555
<?php exit;?>10-18 09:35:05 | 2 | file_put_contents(/project/publics/admin_hd/install_package/caches/caches_template/default/content/message.php): failed to open stream: Permission denied | phpcms/libs/classes/template_cache.class.php | 42
<?php exit;?>10-18 09:35:05 | 2 | chmod(): No such file or directory | phpcms/libs/classes/template_cache.class.php | 43
<?php exit;?>10-18 09:35:05 | 2 | include(/project/publics/admin_hd/install_package/caches/caches_template/default/content/message.php): failed to open stream: No such file or directory | phpcms/libs/functions/global.func.php | 555
<?php exit;?>10-18 09:35:05 | 2 | include(): Failed opening '/project/publics/admin_hd/install_package/caches/caches_template/default/content/message.php' for inclusion (include_path='.:/usr/local/php/lib/php') | phpcms/libs/functions/global.func.php | 555
<?php exit;?>10-18 09:39:13 | 2 | file_put_contents(/project/publics/admin_hd/install_package/caches/caches_template/default/member/login.php): failed to open stream: Permission denied | phpcms/libs/classes/template_cache.class.php | 42
<?php exit;?>10-18 09:39:13 | 2 | chmod(): No such file or directory | phpcms/libs/classes/template_cache.class.php | 43
<?php exit;?>10-18 09:39:13 | 2 | include(/project/publics/admin_hd/install_package/caches/caches_template/default/member/login.php): failed to open stream: No such file or directory | phpcms/modules/member/index.php | 786
<?php exit;?>10-18 09:39:13 | 2 | include(): Failed opening '/project/publics/admin_hd/install_package/caches/caches_template/default/member/login.php' for inclusion (include_path='.:/usr/local/php/lib/php') | phpcms/modules/member/index.php | 786
<?php exit;?>10-18 09:41:39 | 2 | file_put_contents(/project/publics/admin_hd/install_package/caches/caches_template/default/member/login.php): failed to open stream: Permission denied | phpcms/libs/classes/template_cache.class.php | 42
<?php exit;?>10-18 09:41:39 | 2 | chmod(): No such file or directory | phpcms/libs/classes/template_cache.class.php | 43
<?php exit;?>10-18 09:41:39 | 2 | include(/project/publics/admin_hd/install_package/caches/caches_template/default/member/login.php): failed to open stream: No such file or directory | phpcms/modules/member/index.php | 786
<?php exit;?>10-18 09:41:39 | 2 | include(): Failed opening '/project/publics/admin_hd/install_package/caches/caches_template/default/member/login.php' for inclusion (include_path='.:/usr/local/php/lib/php') | phpcms/modules/member/index.php | 786
<?php exit;?>10-18 15:20:20 | 2 | error_log(/project/publics/admin_hd/install_package/caches/pay_error_log.php): failed to open stream: Permission denied | phpcms/modules/pay/respond.php | 117
