<?php
return array (
  'admin' => 
  array (
    'module' => 'admin',
    'name' => 'admin',
    'url' => '',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => 'array (
  \'admin_email\' => \'phpcms@phpcms.cn\',
  \'adminaccessip\' => \'0\',
  \'maxloginfailedtimes\' => \'8\',
  \'maxiplockedtime\' => \'15\',
  \'minrefreshtime\' => \'2\',
  \'mail_type\' => \'1\',
  \'mail_server\' => \'smtp.qq.com\',
  \'mail_port\' => \'25\',
  \'mail_user\' => \'phpcms.cn@foxmail.com\',
  \'mail_auth\' => \'1\',
  \'mail_from\' => \'phpcms.cn@foxmail.com\',
  \'mail_password\' => \'\',
  \'errorlog_size\' => \'20\',
)',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-10-18',
    'updatedate' => '2010-10-18',
  ),
  'member' => 
  array (
    'module' => 'member',
    'name' => '会员',
    'url' => '',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => '{"allowregister":"1","choosemodel":"1","enablemailcheck":"0","enablcodecheck":"0","mobile_checktype":"0","user_sendsms_title":"","registerverify":"0","showapppoint":"0","rmb_point_rate":"10","defualtpoint":"0","defualtamount":"0","showregprotocol":"0","regprotocol":"\\u6b22\\u8fce\\u6ce8\\u518c\\u9ec4\\u9017\\u793e\\u533a ","registerverifymessage":" \\u6b22\\u8fce\\u60a8\\u6ce8\\u518c\\u6210\\u4e3a\\u9ec4\\u9017\\u793e\\u533a\\u7528\\u6237\\uff0c\\u60a8\\u7684\\u8d26\\u53f7\\u9700\\u8981\\u90ae\\u7bb1\\u8ba4\\u8bc1\\uff0c\\u70b9\\u51fb\\u4e0b\\u9762\\u94fe\\u63a5\\u8fdb\\u884c\\u8ba4\\u8bc1\\uff1a{click}\\r\\n\\u6216\\u8005\\u5c06\\u7f51\\u5740\\u590d\\u5236\\u5230\\u6d4f\\u89c8\\u5668\\uff1a{url}","forgetpassword":"\\u9ec4\\u9017\\u793e\\u533a\\u5bc6\\u7801\\u627e\\u56de\\uff0c\\u8bf7\\u5728\\u4e00\\u5c0f\\u65f6\\u5185\\u70b9\\u51fb\\u4e0b\\u9762\\u94fe\\u63a5\\u8fdb\\u884c\\u64cd\\u4f5c\\uff1a{click}\\r\\n\\u6216\\u8005\\u5c06\\u7f51\\u5740\\u590d\\u5236\\u5230\\u6d4f\\u89c8\\u5668\\uff1a{url}"}',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'pay' => 
  array (
    'module' => 'pay',
    'name' => '支付',
    'url' => '',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'digg' => 
  array (
    'module' => 'digg',
    'name' => '顶一下',
    'url' => '',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'special' => 
  array (
    'module' => 'special',
    'name' => '专题',
    'url' => '',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'content' => 
  array (
    'module' => 'content',
    'name' => '内容模块',
    'url' => '',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'search' => 
  array (
    'module' => 'search',
    'name' => '全站搜索',
    'url' => '',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => 'array (
  \'fulltextenble\' => \'1\',
  \'relationenble\' => \'1\',
  \'suggestenable\' => \'1\',
  \'sphinxenable\' => \'0\',
  \'sphinxhost\' => \'10.228.134.102\',
  \'sphinxport\' => \'9312\',
)',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'scan' => 
  array (
    'module' => 'scan',
    'name' => '木马扫描',
    'url' => 'scan',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-01',
    'updatedate' => '2010-09-06',
  ),
  'attachment' => 
  array (
    'module' => 'attachment',
    'name' => '附件',
    'url' => 'attachment',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-01',
    'updatedate' => '2010-09-06',
  ),
  'block' => 
  array (
    'module' => 'block',
    'name' => '碎片',
    'url' => '',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-01',
    'updatedate' => '2010-09-06',
  ),
  'collection' => 
  array (
    'module' => 'collection',
    'name' => '采集模块',
    'url' => 'collection',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-01',
    'updatedate' => '2010-09-06',
  ),
  'dbsource' => 
  array (
    'module' => 'dbsource',
    'name' => '数据源',
    'url' => '',
    'iscore' => '1',
    'version' => '',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-01',
    'updatedate' => '2010-09-06',
  ),
  'template' => 
  array (
    'module' => 'template',
    'name' => '模板风格',
    'url' => '',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-01',
    'updatedate' => '2010-09-06',
  ),
  'release' => 
  array (
    'module' => 'release',
    'name' => '发布点',
    'url' => '',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-01',
    'updatedate' => '2010-09-06',
  ),
  'video' => 
  array (
    'module' => 'video',
    'name' => '视频库',
    'url' => '',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2012-09-28',
    'updatedate' => '2012-09-28',
  ),
  'announce' => 
  array (
    'module' => 'announce',
    'name' => '公告',
    'url' => 'announce/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '公告',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2018-08-30',
    'updatedate' => '2018-08-30',
  ),
  'comment' => 
  array (
    'module' => 'comment',
    'name' => '评论',
    'url' => 'comment/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '评论',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2018-08-30',
    'updatedate' => '2018-08-30',
  ),
  'link' => 
  array (
    'module' => 'link',
    'name' => '友情链接',
    'url' => '',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => 'array (
  1 => 
  array (
    \'is_post\' => \'1\',
    \'enablecheckcode\' => \'0\',
  ),
)',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'vote' => 
  array (
    'module' => 'vote',
    'name' => '投票',
    'url' => '',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => 'array (
  1 => 
  array (
    \'default_style\' => \'default\',
    \'vote_tp_template\' => \'vote_tp\',
    \'allowguest\' => \'1\',
    \'enabled\' => \'1\',
    \'interval\' => \'1\',
    \'credit\' => \'1\',
  ),
)',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'message' => 
  array (
    'module' => 'message',
    'name' => '短消息',
    'url' => '',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'mood' => 
  array (
    'module' => 'mood',
    'name' => '新闻心情',
    'url' => 'mood/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '新闻心情',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2018-08-30',
    'updatedate' => '2018-08-30',
  ),
  'poster' => 
  array (
    'module' => 'poster',
    'name' => '广告模块',
    'url' => 'poster/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '广告模块',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2018-08-30',
    'updatedate' => '2018-08-30',
  ),
  'formguide' => 
  array (
    'module' => 'formguide',
    'name' => '表单向导',
    'url' => 'formguide/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => 'formguide',
    'setting' => 'array (
  \'allowmultisubmit\' => \'1\',
  \'interval\' => \'30\',
  \'allowunreg\' => \'0\',
  \'mailmessage\' => \'用户向我们提交了表单数据，赶快去看看吧。\',
)',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-10-20',
    'updatedate' => '2010-10-20',
  ),
  'wap' => 
  array (
    'module' => 'wap',
    'name' => '手机门户',
    'url' => 'wap/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '手机门户',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2018-08-30',
    'updatedate' => '2018-08-30',
  ),
  'upgrade' => 
  array (
    'module' => 'upgrade',
    'name' => '在线升级',
    'url' => '',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2011-05-18',
    'updatedate' => '2011-05-18',
  ),
  'tag' => 
  array (
    'module' => 'tag',
    'name' => '标签向导',
    'url' => 'tag/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '标签向导',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2018-08-30',
    'updatedate' => '2018-08-30',
  ),
  'sms' => 
  array (
    'module' => 'sms',
    'name' => '短信平台',
    'url' => 'sms/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '短信平台',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2011-09-02',
    'updatedate' => '2011-09-02',
  ),
);
?>